#!/bin/bash
# DO NOT EDIT THIS FILE

ocamlbuild -use-ocamlfind main.cmo state.cmo command.cmo
if [[ $? -ne 0 ]]; then
  cat <<EOF
===========================================================
WARNING

Your code currently does not compile.  You will receive
little to no credit for submitting this code. Check the
error messages above carefully to determine what is wrong.
See a consultant for help if you cannot determine what is
wrong.
===========================================================
EOF
  exit 1
fi

cat >checktypes.ml <<EOF
(* DO NOT EDIT THIS FILE *)
let check_init_state : Yojson.Basic.json -> State.state = State.init_state
let check_win_score : State.state -> int = State.win_score
let check_score : State.state -> int = State.score
let check_turns : State.state -> int = State.turns
let check_current_room_id : State.state -> string = State.current_room_id
let check_inv : State.state -> string list = State.inv
let check_visited : State.state -> string list = State.visited
let check_locations : State.state -> (string*string) list = State.locations
let check_do' : Command.command -> State.state -> State.state = State.do'
let check_parse : string -> Command.command = Command.parse
EOF

if ocamlbuild -use-ocamlfind checktypes.byte ; then
  cat <<EOF
===========================================================
Your function names and types look good to me.
Congratulations!
===========================================================
EOF
else
  cat <<EOF
===========================================================
WARNING

Your function names and types look broken to me.  The code
that you submit might not compile on the grader's machine,
leading to heavy penalties.  Please fix your names and
types.  Check the error messages above carefully to
determine what is wrong.  See a consultant for help if you
cannot determine what is wrong.
===========================================================
EOF
fi

